# Generated by Django 3.2.7 on 2021-09-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdviseFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('type_product', models.CharField(default='Не выбрал продукт', max_length=200, verbose_name='Продукт')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Время запроса')),
                ('state', models.BooleanField(default=False, verbose_name='Провели консультацию')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
